apiVersion: batch/v1
kind: Job
metadata:
  name: gptoss35-server
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: gptoss-vllm-container
          image: nvcr.io/nvidia/pytorch:24.03-py3
          env:
            - name: HF_TOKEN
              value: 
          command: ["/bin/bash", "-c"]
          args:
            - |
              set -euo pipefail
              echo "=== Starting GPT-OSS vLLM server job ==="
              cd /workspace || mkdir -p /workspace && cd /workspace

              rm -rf GptOss35 || true
              echo "[1] Cloning repo..."
              git clone https://github.com/Victowolf/GptOss35.git

              cd GptOss35 || (echo "ERROR: folder not found"; exit 1)

              chmod +x start.sh || true

              echo "[2] Running start.sh ..."
              ./start.sh

              echo "=== GPT-OSS vLLM Server Exited ==="
          resources:
            limits:
              nvidia.com/mig-2g.35gb: 1